// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dtos "github.com/bancodobrasil/featws-api/dtos"
	gitlab "github.com/xanzy/go-gitlab"

	mock "github.com/stretchr/testify/mock"
)

// Gitlab is an autogenerated mock type for the Gitlab type
type Gitlab struct {
	mock.Mock
}

// Connect provides a mock function with given fields:
func (_m *Gitlab) Connect() (*gitlab.Client, error) {
	ret := _m.Called()

	var r0 *gitlab.Client
	if rf, ok := ret.Get(0).(func() *gitlab.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Fill provides a mock function with given fields: rulesheet
func (_m *Gitlab) Fill(rulesheet *dtos.Rulesheet) error {
	ret := _m.Called(rulesheet)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dtos.Rulesheet) error); ok {
		r0 = rf(rulesheet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: rulesheet, commitMessage
func (_m *Gitlab) Save(rulesheet *dtos.Rulesheet, commitMessage string) error {
	ret := _m.Called(rulesheet, commitMessage)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dtos.Rulesheet, string) error); ok {
		r0 = rf(rulesheet, commitMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewGitlab interface {
	mock.TestingT
	Cleanup(func())
}

// NewGitlab creates a new instance of Gitlab. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGitlab(t mockConstructorTestingTNewGitlab) *Gitlab {
	mock := &Gitlab{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
