// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/rulesheets": {
            "post": {
                "security": [
                    {
                        "Authentication Api Key": []
                    },
                    {
                        "Authentication Bearer Token": []
                    }
                ],
                "description": "Nessa operação cria uma folha de regra no banco de dados do FeatWS. Para realizar a criação é necessário completar a folha de regra, com no mínimo:\n- **nome** no parâmetro *name*;\n- **slug** no parâmetro *slug*;\n- **descrição** no parâmetro *description*.\n\n` + "`" + `` + "`" + `` + "`" + `\n{\n\"description\": \"teste no Swagger da API do FeatWS\",\n\"name\": \"teste Swagger API\",\n\"slug\": \"teste_Swagger_API\"\n}\n` + "`" + `` + "`" + `` + "`" + `\nAmbos esses parâmetros devem ser uma string, ou seja, deve estar entre \"aspas\". Não é possível ter uma folha de regra com o mesmo nome de outra.\nPara criar uma folha de regra basta clicar em **Try it out** , complete a folha de regra com os dados desejados, em seguida, clique em **Execute**.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rulesheet"
                ],
                "summary": "Criação de Folha de Regra",
                "parameters": [
                    {
                        "description": "Rulesheet body",
                        "name": "Rulesheet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bancodobrasil_featws-api_payloads_v1.Rulesheet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_bancodobrasil_featws-api_payloads_v1.Rulesheet"
                        },
                        "headers": {
                            "Authorization": {
                                "type": "string",
                                "description": "token access"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Format",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/rulesheets/": {
            "get": {
                "security": [
                    {
                        "Authentication Api Key": []
                    },
                    {
                        "Authentication Bearer Token": []
                    }
                ],
                "description": "É possível listar as folhas de regra de algumas maneiras como veremos a seguir:\n\n- **Sem nenhum parâmetro:** Ao realizar a chamada do endpoint sem a passagem de parâmetros, todas as folhas de regra existentes serão retornadas, contendo informações como nome, ID, e caso estejam disponíveis, descrição e slug.\n- **Usando o *count*:** Ao habilitar o *count* para *True* será retornado do endpoint o número de Folhas de Regras existentes.\n- **Usando o *limit*:** Ao utilizar o parâmetro *limit* deve-se especificar o número máximo de respostas desejadas que serão retornadas pela array.\n- **Usando o *page*:** Ao utilizar o parâmetro *page*, serão retornadas as folhas de regra correspondentes a essa página, onde as folhas são ordenadas em ordem crescente pelo seu ID.\n\nPara listar as folhas de regra basta clicar em **Try it out** , complete com o formado desejados, em seguida, clique em **Execute**.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rulesheet"
                ],
                "summary": "Listar as Folhas de Regra",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Total of results",
                        "name": "count",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max length of the array returned",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number that is multiplied by 'limit' to calculate the offset",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_bancodobrasil_featws-api_payloads_v1.Rulesheet"
                            }
                        },
                        "headers": {
                            "Authorization": {
                                "type": "string",
                                "description": "token access"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Format",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        },
        "/rulesheets/{id}": {
            "get": {
                "security": [
                    {
                        "Authentication Api Key": []
                    },
                    {
                        "Authentication Bearer Token": []
                    }
                ],
                "description": "Para se obter a folha de regra por ID, basta clicar em **Try it out** e colocar o ID desejado em *id*. Em seguida, clique em **Execute** e caso o ID exista retornará a folha de regra com o número de ID desejado.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rulesheet"
                ],
                "summary": "Obter Folha de Regra por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rulesheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_bancodobrasil_featws-api_payloads_v1.Rulesheet"
                            }
                        },
                        "headers": {
                            "Authorization": {
                                "type": "string",
                                "description": "token access"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Format",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Authentication Api Key": []
                    },
                    {
                        "Authentication Bearer Token": []
                    }
                ],
                "description": "Para atualizar ou editar uma folha de regra, é necessário enviar o ID da folha desejada no campo *id*, juntamente com os parâmetros da regra no corpo da solicitação no parâmetro *rulesheet*. Para realizar essa atualização clique no botão **Try it out** e preencher os campos com os dados desejados, em seguida, clicar em **Execute** para enviar a solicitação de atualização.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rulesheet"
                ],
                "summary": "Atualizar Folha de Regra por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rulesheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rulesheet body",
                        "name": "rulesheet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_bancodobrasil_featws-api_payloads_v1.Rulesheet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_bancodobrasil_featws-api_payloads_v1.Rulesheet"
                            }
                        },
                        "headers": {
                            "Authorization": {
                                "type": "string",
                                "description": "token access"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Format",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Authentication Api Key": []
                    },
                    {
                        "Authentication Bearer Token": []
                    }
                ],
                "description": "Para excluir uma folha de regra, é necessário clicar no botão **Try it out** e preencher o campo *id* com o ID da folha de regra que se deseja excluir. Em seguida, clique em **Execute** para enviar a solicitação de exclusão.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rulesheet"
                ],
                "summary": "Deletar Folha de Regra por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rulesheet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "Authorization": {
                                "type": "string",
                                "description": "token access"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Format",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    },
                    "default": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/v1.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_bancodobrasil_featws-api_payloads_v1.Rulesheet": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "features": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "hasStringRule": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "rules": {
                    "type": "object",
                    "additionalProperties": true
                },
                "slug": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1.Error": {
            "type": "object",
            "properties": {
                "error": {},
                "validation_errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ValidationError"
                    }
                }
            }
        },
        "v1.ValidationError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Authentication Api Key": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "Authentication Bearer Token": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "x-extension-openapi": {
        "example": "value on a json format"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9007",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "FeatWS API",
	Description:      "Este projeto consiste em uma API cujo objetivo é fornecer operações para gerenciamento de repositórios e folhas de regra do sistema FeatWS. Através da API, é possível interagir entre a interface de usuário (UI) e o banco de dados, permitindo diversas interações, como as seguintes:\n- [Post] Criação da Folha de Regra;\n- [Get] Listar das Folhas de Regra;\n- [Get] Obter folha de regra por ID;\n- [Put] Atualizar uma folha de regra por ID;\n- [Delete] Deletar uma folha de regra por ID.\n\nAntes de realizar as requisições no Swagger, é necessário autorizar o acesso clicando no botão **Authorize**, ao lado, e inserindo a senha correspondente. Após inserir o campo **value** e clicar no botão **Authorize**, o Swagger estará disponível para ser utilizado.\n",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
